/* Generated by `rules_postgres/lean/Pg/Ir/Emit/UuidC.lean`. */
/* DO NOT EDIT BY HAND. Regenerate via */
/* `rules_postgres/tools/regen/regen-uuid.sh`. */

#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Minimal Postgres type definitions for the standalone C oracle. */
typedef unsigned int Oid;
typedef uintptr_t Datum;
typedef void *fmNodePtr;
#define FLEXIBLE_ARRAY_MEMBER
#define UUID_LEN 16
#define WORDS_BIGENDIAN 0

typedef int16_t int16;
typedef int32_t int32;
typedef int64_t int64;
typedef uint32_t uint32;
typedef uint64_t uint64;

typedef struct
{
	unsigned char data[UUID_LEN];
} pg_uuid_t;

typedef struct NullableDatum
{
	Datum value;
	bool isnull;
} NullableDatum;

struct FmgrInfo;

typedef struct FunctionCallInfoBaseData
{
	struct FmgrInfo *flinfo;
	fmNodePtr context;
	fmNodePtr resultinfo;
	Oid fncollation;
	bool isnull;
	short nargs;
	NullableDatum args[FLEXIBLE_ARRAY_MEMBER];
} FunctionCallInfoBaseData;

/* V1 fmgr calling convention macros. */
#define DatumGetPointer(x) ((void *) (uintptr_t) (x))
#define PG_FUNCTION_ARGS FunctionCallInfoBaseData *fcinfo
#define PG_GETARG_UUID_P(n) ((pg_uuid_t *) DatumGetPointer(fcinfo->args[n].value))
#define PG_GETARG_INT64(n) ((int64) (fcinfo->args[n].value))
#define PG_RETURN_BOOL(x) return (Datum)((x) ? 1 : 0)
#define PG_RETURN_INT32(x) return (Datum) (uint32_t) (x)

/* ─── PG hashfn.h Jenkins/lookup3 implementation ──────────────────
 * Inlined into uuid.c (was previously in the hand-written
 * wrappers_uuid.c, which the oracle shim codegen replaced; the
 * generated shim is pure FFI so it can't carry the helpers).
 * Generic PG helper — used by uuid_hash and uuid_hash_extended below.
 */
#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))
#define mix(a, b, c) { \
    a -= c; a ^= rot(c, 4); c += b; \
    b -= a; b ^= rot(a, 6); a += c; \
    c -= b; c ^= rot(b, 8); b += a; \
    a -= c; a ^= rot(c, 16); c += b; \
    b -= a; b ^= rot(a, 19); a += c; \
    c -= b; c ^= rot(b, 4); b += a; }
#define final(a, b, c) { \
    c ^= b; c -= rot(b, 14); \
    a ^= c; a -= rot(c, 11); \
    b ^= a; b -= rot(a, 25); \
    c ^= b; c -= rot(b, 16); \
    a ^= c; a -= rot(c, 4); \
    b ^= a; b -= rot(a, 14); \
    c ^= b; c -= rot(b, 24); }

static inline uint32_t
read_le32(const unsigned char *k)
{
    return k[0] | (k[1] << 8) | (k[2] << 16) | (k[3] << 24);
}

static Datum
hash_any(const unsigned char *k, int keylen)
{
    uint32_t a = 0x9e3779b9 + keylen + 3923095;
    uint32_t b = a;
    uint32_t c = a;

    a += read_le32(k + 0);
    b += read_le32(k + 4);
    c += read_le32(k + 8);
    mix(a, b, c);
    a += read_le32(k + 12);
    final(a, b, c);

    return (Datum) c;
}

static Datum
hash_any_extended(const unsigned char *k, int keylen, uint64 seed)
{
    uint32_t a = 0x9e3779b9 + keylen + 3923095;
    uint32_t b = a;
    uint32_t c = a;

    if (seed != 0) {
        a += (uint32_t)(seed >> 32);
        b += (uint32_t)seed;
        mix(a, b, c);
    }
    a += read_le32(k + 0);
    b += read_le32(k + 4);
    c += read_le32(k + 8);
    mix(a, b, c);
    a += read_le32(k + 12);
    final(a, b, c);

    return (Datum) (((uint64) b << 32) | (uint64) c);
}

/* Forward declaration of the static helper. */
static int uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2);

static int
uuid_internal_cmp(const pg_uuid_t *arg1, const pg_uuid_t *arg2)
{
	return memcmp(arg1->data, arg2->data, UUID_LEN);
}


Datum
uuid_eq(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) == 0);
}

Datum
uuid_ne(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) != 0);
}

Datum
uuid_lt(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) < 0);
}

Datum
uuid_le(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) <= 0);
}

Datum
uuid_gt(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) > 0);
}

Datum
uuid_ge(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_BOOL(uuid_internal_cmp(arg1, arg2) >= 0);
}

Datum
uuid_cmp(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *arg1 = PG_GETARG_UUID_P(0);
	pg_uuid_t  *arg2 = PG_GETARG_UUID_P(1);

	PG_RETURN_INT32(uuid_internal_cmp(arg1, arg2));
}


Datum
uuid_hash(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *key = PG_GETARG_UUID_P(0);

	return hash_any(key->data, UUID_LEN);
}

Datum
uuid_hash_extended(PG_FUNCTION_ARGS)
{
	pg_uuid_t  *key = PG_GETARG_UUID_P(0);

	return hash_any_extended(key->data, UUID_LEN, PG_GETARG_INT64(1));
}
