/*
 * pgpb_to_lean_ast — emit Lean source values of Pg.Query.ParseResult
 * from a .pgpb byte payload.
 *
 * The trust-chain leg per the design doc §7 (b):
 *
 *   .sql ─sql_to_protobuf─► .pgpb ─pgpb_to_lean_ast─► .lean
 *                                                       │ leanc
 *                                                       ▼
 *                                       Pg.Query.ParseResult value
 *
 * The emitted .lean imports `Pg.Query.Generated` (Phase 2's stubbed
 * DDL slice) and defines a single `def parseResult : ParseResult`
 * matching the byte payload. Lean kernel-checks that the value
 * inhabits the generated type — if pgpb_to_lean_ast's output is
 * malformed (mis-encoded ByteArray literal, wrong field name, etc.)
 * the build breaks at this point.
 *
 * For each top-level Node payload, we re-pack the Node back to its
 * marshalled bytes via protobuf-c's `pg_query__node__pack`. The
 * stubbed Pg.Query.RawStmt has `stmt : ByteArray`, so the payload
 * is just the opaque bytes — consumers decode further on demand
 * (e.g. via a future pure-Lean proto-3 decoder, or by re-running
 * pgpb_to_lean_ast on a sub-payload with a different stub set).
 *
 * Exit codes:
 *   0  — emitted successfully
 *   1  — argv error
 *   2  — input read / unpack failure
 *
 * ~80% structure reuse from pgpb_to_snapshot.c (slurp, unpack,
 * top-level loop). The difference is the emit shape: opaque
 * ByteArray literals for each Node rather than walking each
 * stmt's typed fields.
 */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "pg_query.pb-c.h"

/* ─── File I/O ──────────────────────────────────────────────────── */

static unsigned char *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "pgpb_to_lean_ast: %s: %s\n", path, strerror(errno));
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 0) { fclose(f); return NULL; }
    unsigned char *buf = (unsigned char *)malloc((size_t)sz);
    if (!buf) { fclose(f); return NULL; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    *out_len = n;
    return buf;
}

/* ─── Lean ByteArray-literal emitter ────────────────────────────── */

/* Emit a Lean `_root_.ByteArray` literal from raw bytes.
 *
 * Format: `(⟨#[0xAB, 0xCD, ...]⟩ : ByteArray)` — wraps a
 * `UInt8` array via the `ByteArray.mk` anonymous-constructor
 * notation. For empty buffers, emit `ByteArray.empty` so the
 * generated value matches the generated structure's default.
 */
static void emit_bytearray_literal(FILE *o,
                                   const unsigned char *bytes,
                                   size_t len) {
    if (len == 0) {
        fputs("_root_.ByteArray.empty", o);
        return;
    }
    fputs("(\xe2\x9f\xa8#[", o);
    for (size_t i = 0; i < len; i++) {
        if (i) fputs(", ", o);
        fprintf(o, "0x%02X", bytes[i]);
    }
    fputs("]\xe2\x9f\xa9 : _root_.ByteArray)", o);
}

/* ─── ParseResult emission ──────────────────────────────────────── */

static void emit_raw_stmt(FILE *o, const PgQuery__RawStmt *rs) {
    /* Re-pack the Node sub-message back to bytes. The unpacked
     * PgQuery__Node sits in memory; protobuf-c's pg_query__node__pack
     * serializes it to the buffer we provide. */
    fputs("    { stmt := ", o);
    if (!rs->stmt) {
        fputs("_root_.ByteArray.empty", o);
    } else {
        size_t need = pg_query__node__get_packed_size(rs->stmt);
        unsigned char *buf = (unsigned char *)malloc(need);
        if (!buf) {
            fputs("_root_.ByteArray.empty /- ENOMEM during pack -/", o);
        } else {
            size_t got = pg_query__node__pack(rs->stmt, buf);
            emit_bytearray_literal(o, buf, got);
            free(buf);
        }
    }
    fprintf(o, ",\n      stmtLocation := %d,\n      stmtLen := %d }",
            rs->stmt_location, rs->stmt_len);
}

static void emit_parse_result(FILE *o, const PgQuery__ParseResult *pr,
                              const char *module_name) {
    fprintf(o, "/- Auto-generated by @rules_postgres//tools:pgpb_to_lean_ast.\n"
               "   DO NOT EDIT BY HAND \xe2\x80\x94 regenerate from a .pgpb input. -/\n\n");
    fprintf(o, "import Pg.Query.Generated\n\n");
    fprintf(o, "namespace %s\n\n", module_name);
    fprintf(o, "open Pg.Query\n\n");

    fprintf(o, "/-- `ParseResult` decoded from the input .pgpb bytes.\n"
               "    The Lean kernel typechecks this value against the\n"
               "    structure generated by `pgpb_codegen` \xe2\x80\x94 a malformed\n"
               "    decoder output breaks the build at module load. -/\n");
    fprintf(o, "def parseResult : ParseResult where\n");
    fprintf(o, "  version := %d\n", pr->version);

    if (pr->n_stmts == 0) {
        fprintf(o, "  stmts   := []\n");
    } else {
        fprintf(o, "  stmts   :=\n  [\n");
        for (size_t i = 0; i < pr->n_stmts; i++) {
            emit_raw_stmt(o, pr->stmts[i]);
            if (i + 1 < pr->n_stmts) fputs(",\n", o);
            else fputs("\n", o);
        }
        fprintf(o, "  ]\n");
    }
    fprintf(o, "\n");
    fprintf(o, "end %s\n", module_name);
}

/* ─── main ──────────────────────────────────────────────────────── */

int main(int argc, char **argv) {
    const char *module = NULL;
    const char *output = NULL;
    const char *input = NULL;
    int argi = 1;
    while (argi < argc) {
        if (strcmp(argv[argi], "--module") == 0 && argi + 1 < argc) {
            module = argv[++argi];
        } else if (strcmp(argv[argi], "--output") == 0 && argi + 1 < argc) {
            output = argv[++argi];
        } else if (argv[argi][0] != '-') {
            input = argv[argi];
        } else {
            fprintf(stderr, "pgpb_to_lean_ast: unknown arg %s\n", argv[argi]);
            return 1;
        }
        argi++;
    }
    if (!module || !output || !input) {
        fprintf(stderr, "usage: pgpb_to_lean_ast --module <NAME> "
                        "--output <FILE> <input.pgpb>\n");
        return 1;
    }

    size_t n = 0;
    unsigned char *buf = read_file(input, &n);
    if (!buf) return 2;

    PgQuery__ParseResult *pr = pg_query__parse_result__unpack(NULL, n, buf);
    free(buf);
    if (!pr) {
        fprintf(stderr, "pgpb_to_lean_ast: failed to unpack %s\n", input);
        return 2;
    }

    FILE *out = fopen(output, "w");
    if (!out) {
        fprintf(stderr, "pgpb_to_lean_ast: cannot open %s: %s\n",
                output, strerror(errno));
        pg_query__parse_result__free_unpacked(pr, NULL);
        return 2;
    }

    emit_parse_result(out, pr, module);
    fclose(out);
    fprintf(stderr, "  %s: %zu stmts \xe2\x86\x92 %s\n",
            input, pr->n_stmts, output);
    pg_query__parse_result__free_unpacked(pr, NULL);
    return 0;
}
