/-
Pg.Stmt — Top-level PG statement structures (CREATE FUNCTION,
CREATE TABLE, CREATE TRIGGER, CREATE DOMAIN, CREATE POLICY, etc.)
and the master `Stmt` inductive.

Sibling to `Pg.Ast` (which holds Expr/BodyStmt/SelectSource and
the supporting types Identifier/FuncParam/Volatility/RowAlias/
ConflictUpdate/ConflictAction). Pg.Stmt builds the DDL surface
on top of the Expr/BodyStmt layer.

Moved from Aion's `lean/Aion/Db/PgAst.lean` lines 1295-2128
as part of PgAst extraction Phase 1b Step 3. The split is:

  Pg.Ast    — DML / expression layer (Expr, BodyStmt, …)
  Pg.Stmt   — DDL / statement layer (Create*Stmt, Stmt, …)

Some structures here (ReferentialAction, TableConstraint,
ColumnDef, IndexElem, CreateIndexStmt, CreateSchemaStmt,
TriggerTiming/Event/Level) duplicate generic shapes in
`Polyglot.Sql.Ast`. The duplicates exist because Aion's
versions reference Pg-specific types (`Pg.Ast.Expr`,
`Pg.Ty.PgType`) directly — de-duplication against the
parameterized Polyglot generics is a follow-up cleanup.
-/

import Pg.Ast
import Pg.Ty

namespace Pg.Stmt

open Pg.Ast
open Pg.Ty

/-- A complete CREATE FUNCTION statement — the PL/pgSQL function
    declaration libpg_query represents as `CreateFunctionStmt`.

    `body` is a list of `BodyStmt`s wrapped in BEGIN/END. The list
    shape is intentional: it matches the linear sequence of
    statements PL/pgSQL accepts inside a function body. -/
structure CreateFunctionStmt where
  /-- Schema-qualified function name (e.g. `graph.has_permission_v2`).
      Catalog-grounded: typed as `Identifier` (≡ `Catalog.QualifiedName`)
      so the same value drives both the bare SQL emission via
      `Identifier.toSql` AND catalog resolution via
      `Snapshot.resolveProc`. Migrated from `String` in Track R A1a. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- Return type (e.g. `BOOLEAN`, `BIGINT`). -/
  returnType : PgType
  /-- Volatility class — STABLE/IMMUTABLE/VOLATILE. -/
  volatility : Volatility
  /-- SECURITY DEFINER means the function runs with the privileges
      of its owner (typically `app_admin`); the alternative
      (SECURITY INVOKER) is the default. We default to DEFINER for
      anything reading session state via SECURITY-DEFINER helpers. -/
  securityDefiner : Bool
  /-- The function body — a sequence of PL/pgSQL statements. -/
  body : List BodyStmt
  /-- Local-variable declarations appearing in the PL/pgSQL
      `DECLARE` block (between `AS $$` and `BEGIN`). Each entry
      reuses `FuncParam` (name + type) because syntactically a
      local declaration and a function parameter have the same
      shape. Empty list (the default) means no DECLARE block is
      emitted. Production
      `invalidate_permission_cache_on_statement` uses this for
      the per-TG_OP id variables. -/
  declare : List FuncParam := []
  /-- Optional banner comment (header lines emitted before the
      CREATE FUNCTION). Used by PgEmit to attach a "generated by …"
      provenance comment; empty list means no banner. -/
  banner : List String := []
  /-- When `true`, emit `RETURNS SETOF <returnType>` instead of
      the bare `RETURNS <returnType>` shape. Ignored when
      `returnTable` is `some` (which takes precedence).
      Production users include `auth.jwt_validate_audience`
      and similar SETOF-of-a-named-row-type functions.

      Added alongside `returnTable` to unblock the
      `returnQuerySelect` BodyStmt constructor (slice 1) —
      RETURN QUERY SELECT requires the enclosing function to
      have a SETOF or TABLE return shape. -/
  returnSetOf : Bool := false
  /-- When `some`, emit `RETURNS TABLE (<col₁> <ty₁>, …)`
      instead of `RETURNS <returnType>` (or
      `RETURNS SETOF <returnType>`). The `returnType` field is
      ignored when this is `some`; postgres derives the return
      row type from the table column list directly.

      Production users include `auth.jwt_validate_claims`,
      `auth.jwt_validate_audience`, and `auth.jwt_map_claims_to_context`
      whose result-set rows are `(valid BOOLEAN, error_message TEXT)`
      or similar inline-typed tuples. -/
  returnTable : Option (List (String × PgType)) := none

/-- A CREATE FUNCTION whose body is **pure SQL** — a single
    expression evaluated via `SELECT`. The `LANGUAGE SQL` form is
    declarative: no IF/RETURN procedural control, no PL/pgSQL
    variables, no exception handling. Functions of this shape
    have a *much* smaller operational-semantics surface than
    PL/pgSQL — pure relational algebra + scalar expressions —
    and PostgreSQL's planner can inline them at call sites.

    Track C of the runtime-emit strategy: every PL/pgSQL function
    we can express as a single SQL expression should migrate to
    this shape, dropping PL/pgSQL operational semantics from the
    trust chain.

    The body is a single `Expr` (compared to `BodyStmt` for
    PL/pgSQL); the function returns `SELECT <body>` at call time. -/
structure CreateSqlFunctionStmt where
  /-- Schema-qualified function name. Catalog-grounded via
      `Identifier` (≡ `Catalog.QualifiedName`). Migrated from
      `String` in Track R A1a alongside `CreateFunctionStmt.name`. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- Return type. -/
  returnType : PgType
  /-- Volatility class. -/
  volatility : Volatility
  /-- SECURITY DEFINER vs INVOKER. -/
  securityDefiner : Bool
  /-- The function body — one SQL expression. -/
  body : Expr
  /-- Optional banner. -/
  banner : List String := []

/-- A single non-recursive Common Table Expression: `WITH <name>
    AS (SELECT <projections> FROM <source> [WHERE <where>])`.
    Used as an optional `withCte` field on the TABLE-returning
    and scalar-select function stmts.

    Recursive CTEs use the dedicated `CreateRecursiveCteFunctionStmt`
    (which has its own UNION ALL + recursive case structure). -/
structure WithCte where
  /-- CTE name (referenced in the outer query as a table). -/
  name : String
  /-- Optional explicit column names for the CTE's output, emitted
      as `<name>(col1, col2, …) AS (...)`. Empty list means
      postgres infers column names from the projection list (which
      works for `.var "x"` and `.field tbl "x"` but produces
      auto-names like `count`, `coalesce` for unnamed aggregate /
      function-call projections — at which point downstream
      references to the CTE will fail to find the expected
      column). Use when any projection is an unaliased expression.

      Added in PR-PLPGSQL-5 to support `audit.get_statistics`'s
      hoisted `type_stats(event_type, event_count)` and
      `schema_stats(schema_name, event_count)` CTEs. -/
  columnNames : List String := []
  /-- Projections of the CTE's SELECT. -/
  projections : List Expr
  /-- FROM source. Use `SelectSource.empty` for no FROM. -/
  source : SelectSource
  /-- Optional WHERE filter. -/
  whereCond : Option Expr
  /-- Optional `GROUP BY <expr1>, <expr2>, …` clause. Empty list
      means no GROUP BY. Extended in PR-PLPGSQL-5 to support
      `audit.get_statistics`'s per-(event_type, schema_name)
      rollups. -/
  groupBy : List Expr := []
  /-- Optional `ORDER BY <expr> [DESC|ASC], …` clause. Empty list
      means no ORDER BY. `(expr, true)` is DESC, `(expr, false)`
      is ASC — matching `CreateTableReturningFunctionStmt.orderBy`'s
      shape. -/
  orderBy : List (Expr × Bool) := []
  /-- Optional `LIMIT <expr>` clause. Used by the
      `recent_events`-style CTE that wraps a `LIMIT
      p_recent_activity_limit`-sliced subset. -/
  limit : Option Expr := none

/-- A LANGUAGE SQL function that returns a set of rows via
    `RETURNS SETOF <rowType>`. Different from
    `CreateSqlFunctionStmt` (scalar return) in that the body
    projects rows from a source rather than evaluating to a
    single scalar.

    Body shape:

      SELECT <projectAlias>.* | *  FROM <source>
       [WHERE <whereCond>]
       [ORDER BY <orderBy>]
       [LIMIT <limit>]

    The `source` is a `SelectSource` — a single table or a
    JOIN tree. The `projectAlias` selects `<alias>.*` rather than
    `*` (needed when joining: `SELECT s.*` projects only the
    statement columns, not the cross-product). When `none`,
    emits `*`.

    Production usage:
      * `graph.get_resource(BIGINT) RETURNS SETOF graph.RESOURCE`
      * `graph.get_resource_by_external_id(...) RETURNS SETOF graph.RESOURCE`
      * `graph.get_statement(BIGINT) RETURNS SETOF graph.STATEMENT`
      * `graph.get_statements(...) RETURNS SETOF graph.STATEMENT`
        — uses JOIN against graph.resource (PR-SQL-10a addition) -/
structure CreateSetReturningFunctionStmt where
  /-- Schema-qualified function name. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- The row type yielded by SETOF — typically a user-defined
      composite type matching the source table's row shape
      (`graph.RESOURCE`, `graph.STATEMENT`). Encoded as
      `PgType.userDefined "graph.RESOURCE"`. -/
  rowType : PgType
  /-- Volatility class — typically STABLE for read-only lookups. -/
  volatility : Volatility
  /-- SECURITY DEFINER (true) vs INVOKER (false). Production
      lookup functions tend to use INVOKER so the caller's RLS
      policies apply. -/
  securityDefiner : Bool
  /-- FROM source — a table (with optional alias) or a JOIN tree. -/
  source : SelectSource
  /-- Optional alias whose `.*` is projected. When `none` emits
      bare `*`. Required when `source` is a JOIN and the function
      returns only one side's row type (e.g. `SELECT s.*` from
      `graph.statement s JOIN graph.resource prd`). -/
  projectAlias : Option String
  /-- Optional `WHERE <cond>` filter. -/
  whereCond : Option Expr
  /-- `ORDER BY <expr1> [DESC|ASC] [, <expr2> [DESC|ASC] …]`.
      Empty list means no ORDER BY. -/
  orderBy : List (Expr × Bool)
  /-- Optional `LIMIT <n>`. -/
  limit : Option Nat
  /-- Optional banner. -/
  banner : List String := []

/-- A LANGUAGE SQL function that returns a result set described
    inline via `RETURNS TABLE (col1 T1, col2 T2, …)`. Differs
    from `CreateSetReturningFunctionStmt` (which returns SETOF
    of a named row type) in that the column shape is declared
    in the signature, the body projects an explicit column list
    (each column an arbitrary `Expr`), and LIMIT/OFFSET accept
    parameter-bound `Expr` values (not just `Nat` literals).

    Production usage:
      * `audit.get_table_parts(REGCLASS) RETURNS TABLE
         (schema_name TEXT, table_name TEXT)` — pg_class JOIN
         pg_namespace with text-cast column projections.
      * `graph.query_resources_by_type(LTREE, INTEGER DEFAULT NULL,
         INTEGER DEFAULT 0) RETURNS TABLE (id BIGINT)` — single-
         table scan with parameter-bound LIMIT + OFFSET.

    The `projects` list must have the same length as `tableCols`
    (Postgres enforces matching count + types at function-creation
    time). We don't enforce that here at the AST level. -/
structure CreateTableReturningFunctionStmt where
  /-- Schema-qualified function name. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- `RETURNS TABLE (col1 T1, col2 T2, …)` column list. -/
  tableCols : List (String × PgType)
  /-- Volatility class. -/
  volatility : Volatility
  /-- SECURITY DEFINER vs INVOKER. -/
  securityDefiner : Bool
  /-- Projected columns of the SELECT — each is an `Expr` so it
      can be a field reference (`r.id`), a typed cast
      (`n.nspname::TEXT`), a function call, etc. Must align with
      `tableCols` in length (Postgres rejects mismatches). -/
  projects : List Expr
  /-- FROM source — table, JOIN tree, function call, or `.empty`
      for a no-FROM SELECT (postgres accepts `SELECT expr1, expr2`
      with no FROM clause, returning exactly one row). Used by
      `util.get_connection_info` which projects pseudo-constants
      and pg_* function calls without any table source. -/
  source : SelectSource
  /-- Optional `WHERE <cond>` filter. -/
  whereCond : Option Expr
  /-- `ORDER BY <expr1> [DESC|ASC] [, <expr2> [DESC|ASC] …]`.
      Empty list means no ORDER BY. -/
  orderBy : List (Expr × Bool)
  /-- Optional `LIMIT <expr>`. Unlike `CreateSetReturningFunctionStmt`
      this accepts an arbitrary `Expr` so it can be a parameter
      reference (e.g. `LIMIT p_limit`). Pass `some (.litConst (.int 1))`
      for a literal. -/
  limit : Option Expr
  /-- Optional `OFFSET <expr>`. Same `Expr`-shaped flexibility as
      `limit` — supports parameter-bound offsets like
      `OFFSET p_offset`. -/
  offset : Option Expr
  /-- Non-recursive CTE prefix: zero or more `WITH <cte> AS (...)`
      clauses, comma-separated. When non-empty, the body renders as
      `WITH cte1 AS (...), cte2 AS (...), … SELECT … FROM <main_source>`.
      Each CTE's name is referenced from later CTEs or from `source`
      as a virtual table via `SelectSource.table cteName ...`.
      Empty list means no CTE prefix.

      Generalized from `Option WithCte` in PR-PLPGSQL-4 to support
      `audit.get_statistics`, whose body composes three sequential
      CTEs (`filtered_events`, `type_counts`, `schema_counts`). -/
  withCte : List WithCte := []
  /-- Whether to emit `SELECT DISTINCT` instead of bare `SELECT`. -/
  distinct : Bool := false
  /-- Optional `GROUP BY <expr1>, <expr2>, …` clause. Empty list
      means no GROUP BY. Required when the SELECT mixes
      aggregates (COUNT, SUM, etc.) with non-aggregated columns. -/
  groupBy : List Expr := []
  /-- Optional banner. -/
  banner : List String := []

/-- A LANGUAGE SQL function whose body is a scalar SELECT with a
    `FROM` source (possibly a JOIN tree). Differs from
    `CreateSqlFunctionStmt` (body=Expr, no FROM) and from
    `Expr.selectScalar` (single-table FROM only, no JOIN) in
    that the body is `SELECT <scalarExpr> FROM <SelectSource>
    [WHERE …]` and returns a single scalar value (not a row set,
    not a TABLE-shaped record set).

    Production usage:
      * `graph.count_workspace_resources(BIGINT, UUID DEFAULT NULL,
         LTREE DEFAULT NULL) RETURNS BIGINT` — counts joined rows
         via `SELECT COUNT(*) FROM graph.resource r INNER JOIN
         graph.permission_cache pc ON … WHERE …`. -/
structure CreateScalarSelectFunctionStmt where
  /-- Schema-qualified function name. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- Return type — the type of the scalar projection. -/
  returnType : PgType
  /-- Volatility class. -/
  volatility : Volatility
  /-- SECURITY DEFINER vs INVOKER. -/
  securityDefiner : Bool
  /-- The projected scalar expression (e.g. `Expr.countStar`,
      `Expr.callBuiltin "MAX" [.field …]`). -/
  project : Expr
  /-- FROM source — table or JOIN tree. -/
  source : SelectSource
  /-- Optional `WHERE <cond>` filter. -/
  whereCond : Option Expr
  /-- Non-recursive CTE prefix: zero or more `WITH <cte> AS (...)`
      clauses, comma-separated. Empty list = no CTE prefix.
      Generalized from `Option WithCte` in PR-PLPGSQL-4. -/
  withCte : List WithCte := []
  /-- Optional banner. -/
  banner : List String := []

/-- A `CYCLE` clause on a `WITH RECURSIVE` CTE. Postgres path-
    tracks the named columns; when a row repeats by those
    columns, `flagCol` becomes `true` and `pathCol` is the array
    of visited values. The outer SELECT typically filters with
    `WHERE NOT <flagCol>` to suppress cycle-completing rows.

    Production `auth.get_descendants` lacks this clause and
    only catches DIRECT self-loops via a manual `WHERE
    s.key_id <> p_parent_key_id` predicate. Multi-hop cycles
    (a → b → a) cause unbounded recursion — defect-10 DOS. -/
structure CycleClause where
  /-- The cycle-identifying column. Postgres compares rows by
      this column's value across recursive expansion. (Postgres
      allows multiple columns separated by commas; we model the
      single-column case which covers the defect-10 fix.) -/
  column : String
  /-- Output cycle-flag column name (boolean; `true` when the
      row would close a cycle). -/
  flagCol : String
  /-- Output path column name (an array of visited values). -/
  pathCol : String

/-- A LANGUAGE SQL function whose body is a `WITH RECURSIVE`
    CTE followed by a `SELECT * FROM <cteName>` outer query.
    Models the postgres recursive-CTE shape used by tree/graph
    traversal helpers like `auth.build_keychain`,
    `auth.get_descendants`, and `graph.traverse`.

    Body layout:

      WITH RECURSIVE <cteName> AS (
        SELECT <baseProjections>
        FROM <baseSource>
        [WHERE <baseWhere>]
        UNION ALL
        SELECT <recursiveProjections>
        FROM <recursiveSource>     -- typically joins back to <cteName>
        [WHERE <recursiveWhere>]
      )
      SELECT * FROM <cteName>
      [WHERE <outerWhere>]
      [ORDER BY <outerOrderBy>]
      [LIMIT <outerLimit>]
      [OFFSET <outerOffset>]

    The recursive case typically references the CTE via
    `SelectSource.table cteName (some "alias")` and joins back
    to the auth.secrets / graph.statement / etc. source.

    Postgres requires `baseProjections` and
    `recursiveProjections` to have matching length and
    compatible column types — this is enforced by the libpg_query
    parse gate, not at the AST level. -/
structure CreateRecursiveCteFunctionStmt where
  /-- Schema-qualified function name. -/
  name : Identifier
  /-- Function parameters in declaration order. -/
  params : List FuncParam
  /-- `RETURNS TABLE (col1 T1, col2 T2, …)` column list. Must
      match the CTE column shape. -/
  tableCols : List (String × PgType)
  /-- Volatility class. -/
  volatility : Volatility
  /-- SECURITY DEFINER vs INVOKER. -/
  securityDefiner : Bool
  /-- CTE name introduced by `WITH RECURSIVE <name> AS (…)`. -/
  cteName : String
  /-- Projections of the base SELECT. -/
  baseProjections : List Expr
  /-- FROM source of the base SELECT. -/
  baseSource : SelectSource
  /-- Optional WHERE of the base SELECT. -/
  baseWhere : Option Expr
  /-- Projections of the recursive SELECT (same arity as base). -/
  recursiveProjections : List Expr
  /-- FROM source of the recursive SELECT — typically joins
      `<cteName>` back to the data source. -/
  recursiveSource : SelectSource
  /-- Optional WHERE of the recursive SELECT. -/
  recursiveWhere : Option Expr
  /-- Optional WHERE on the outer `SELECT * FROM <cteName>`. -/
  outerWhere : Option Expr
  /-- Optional ORDER BY on the outer SELECT. -/
  outerOrderBy : List (Expr × Bool)
  /-- Optional LIMIT on the outer SELECT. -/
  outerLimit : Option Expr
  /-- Optional OFFSET on the outer SELECT. -/
  outerOffset : Option Expr
  /-- Optional `CYCLE col SET flag USING path` clause. When set,
      postgres path-tracks rows by `col` to detect cycles; the
      cycle flag and path arrays appear as extra columns on the
      CTE result. -/
  cycle : Option CycleClause := none
  /-- Optional banner. -/
  banner : List String := []

/-- A column definition inside a CREATE TABLE. Mirrors libpg_query's
    `ColumnDef` node for the subset our emitter produces:
    name + type + optional NOT NULL + optional DEFAULT expression.

    `pgType : PgType` is now a closed inductive (Tightening B); the
    surface SQL keyword is rendered via `PgType.toSql`. -/
structure ColumnDef where
  name : String
  pgType : PgType
  notNull : Bool := false
  /-- Optional DEFAULT clause, rendered as `DEFAULT <expr>`. -/
  default : Option Expr := none
  /-- Optional `GENERATED ALWAYS AS (<expr>) STORED` clause. When
      set, Postgres computes this column from the expression on
      every insert/update and rejects manual writes to the
      column. Used by `auth.secrets.key_id`
      (`key_name || '-v' || key_version`). Mutually exclusive
      with `default` in practice (PG rejects both being set), but
      we don't enforce that at the AST level. -/
  generatedAs : Option Expr := none

/-- Foreign-key referential action — postgres's `ON DELETE` /
    `ON UPDATE` clauses. Mirrors libpg_query's `FKCONSTR_ACTION_*`
    enum values for the actions we actually emit. -/
inductive ReferentialAction where
  | noAction   : ReferentialAction  -- the default; reject the modification
  | restrict   : ReferentialAction  -- like noAction but checked immediately
  | cascade    : ReferentialAction  -- propagate the modification to FKs
  | setNull    : ReferentialAction  -- set the FK column(s) to NULL
  | setDefault : ReferentialAction  -- set the FK column(s) to DEFAULT
deriving DecidableEq

/-- Render a referential action as the SQL keyword phrase. -/
def ReferentialAction.toSql : ReferentialAction → String
  | .noAction   => "NO ACTION"
  | .restrict   => "RESTRICT"
  | .cascade    => "CASCADE"
  | .setNull    => "SET NULL"
  | .setDefault => "SET DEFAULT"

/-- A table-level constraint. Mirrors libpg_query's `Constraint`
    node, discriminated by `contype`. The constructors cover the
    subset our emitter produces; CHECK / EXCLUDE constraints will
    join as savvi-studio's schema requires.

    All variants render as `CONSTRAINT name <body>` when an explicit
    name is provided, or anonymous `<body>` otherwise (postgres
    auto-names anonymous constraints). -/
inductive TableConstraint where
  | primaryKey
      (columns : List String)
      (name : Option String := none) : TableConstraint
  | unique
      (columns : List String)
      (name : Option String := none) : TableConstraint
  -- `foreignKey` with optional `deferrable` flag — when true,
  -- emits `DEFERRABLE INITIALLY DEFERRED`. Used by
  -- `auth.secrets.fk_parent_key` so the parent-key chain can be
  -- constructed within a transaction even when the referenced
  -- parent row doesn't exist yet (would exist by COMMIT).
  -- Defaults to `false` (the non-deferrable form every other
  -- production FK uses).
  | foreignKey
      (columns : List String)
      (refTable : String)
      (refColumns : List String)
      (onDelete : Option ReferentialAction := none)
      (onUpdate : Option ReferentialAction := none)
      (name : Option String := none)
      (deferrable : Bool := false) : TableConstraint
  | check
      (expr : Expr)
      (name : Option String := none) : TableConstraint

/-- Postgres partitioning strategy. Mirrors libpg_query's
    `PARTITION_STRATEGY_*` enum. `range` is the only strategy our
    schema uses today (`audit.events` partitions by month on
    `event_time`); `list` and `hash` join when production needs
    them. -/
inductive PartitionStrategy where
  | range : PartitionStrategy
  | list  : PartitionStrategy
  | hash  : PartitionStrategy
deriving DecidableEq

/-- Render a partition strategy as the SQL keyword. -/
def PartitionStrategy.toSql : PartitionStrategy → String
  | .range => "RANGE"
  | .list  => "LIST"
  | .hash  => "HASH"

/-- A `PARTITION BY <strategy> (<columns>)` clause on a CREATE
    TABLE. Production uses this on `audit.events` to partition the
    high-volume audit log by month on `event_time`; new partitions
    are created via `audit.create_partition_for_month()` and
    `ALTER TABLE … ATTACH PARTITION` in the partition-management
    functions.

    The partition columns must be part of every UNIQUE / PRIMARY
    KEY constraint on the table (a postgres rule); `audit.events`
    encodes this by using `PRIMARY KEY (id, event_time)` even
    though `id` is the natural row identity. The AST does not
    enforce that rule today — the libpg_query parse gate catches
    violations at SQL surface. -/
structure PartitionBy where
  strategy : PartitionStrategy
  columns  : List String
deriving DecidableEq

/-- A complete CREATE TABLE statement. Mirrors libpg_query's
    `CreateStmt` node for the (schema-qualified) table-name +
    column-list + table-constraint shape. -/
structure CreateTableStmt where
  /-- Schema-qualified table name (e.g. `graph.resource`). -/
  name : Identifier
  /-- Column list in declaration order. -/
  columns : List ColumnDef
  /-- Table-level constraints (PRIMARY KEY, UNIQUE, FOREIGN KEY,
      CHECK), rendered after the column list inside the same
      parenthesized body. Empty list means no table constraints
      (column-level NOT NULL / DEFAULT still apply). -/
  constraints : List TableConstraint := []
  /-- If true, emits `CREATE TABLE IF NOT EXISTS` instead of the
      bare form — the idempotent shape used in migrations. -/
  ifNotExists : Bool := false
  /-- Optional banner comment (header lines emitted before the
      CREATE TABLE). Same convention as `CreateFunctionStmt`. -/
  banner : List String := []
  /-- Optional `PARTITION BY <strategy> (<columns>)` clause.
      Production uses this on `audit.events` (PARTITION BY RANGE
      on `event_time`). When set, the printer emits the clause
      between the table body's closing `)` and the terminating
      `;`. -/
  partitionBy : Option PartitionBy := none

/-- An index method — the access-method postgres uses to organize
    the index entries. Mirrors libpg_query's `accessMethod` field on
    `IndexStmt`. We model the canonical methods we actually emit;
    extension methods (gin / gist for full-text) join as needed. -/
inductive IndexMethod where
  | btree : IndexMethod  -- default, range + equality lookups
  | hash  : IndexMethod  -- equality-only, fast point lookup
  -- Generalized Search Tree — used for ltree-path / geometric /
  -- range types. Production uses `gist (kind)` on graph.resource
  -- for path-based ltree lookups.
  | gist  : IndexMethod
  -- Generalized Inverted Index — used for JSONB / array / fulltext.
  -- Production uses `gin (data)` on graph.resource and
  -- graph.statement for `data @> ...` containment lookups.
  | gin   : IndexMethod
deriving DecidableEq

/-- Render an `IndexMethod` as the SQL keyword. -/
def IndexMethod.toSql : IndexMethod → String
  | .btree => "btree"
  | .hash  => "hash"
  | .gist  => "gist"
  | .gin   => "gin"

/-- An index column entry — the column-name part of an
    `IndexElem`. Mirrors libpg_query's `IndexElem` for the simple
    column-reference case (we don't yet emit expression-indices or
    operator-class clauses). -/
structure IndexElem where
  column : String
  /-- Optional operator class, e.g. `gist_ltree_ops` on an `ltree` GiST index.

      Postgres picks a default opclass per (type, access method), and for the
      common cases that default is what you want — so this stays optional. It
      matters when the default is not the intended one: an `ltree` column under
      GiST has more than one sensible opclass, and which one is chosen decides
      whether `<@` ancestor matching uses the index or sequentially scans. That
      is a correctness-shaped performance property, and a schema that cannot
      state it has to hope. -/
  opclass : Option String := none
deriving DecidableEq

/-- A complete CREATE INDEX statement. Mirrors libpg_query's
    `IndexStmt` for the subset we emit:
      * named (vs anonymous) index
      * single-table target
      * btree/hash access method
      * one or more column elements
      * optional `IF NOT EXISTS` (idempotent migration shape)
      * optional `UNIQUE` modifier (single-row-per-key constraint) -/
structure CreateIndexStmt where
  /-- Index name (typically schema-prefixed, e.g. `graph.resource_kind_idx`). -/
  name : Identifier
  /-- Schema-qualified target table (e.g. `graph.resource`). -/
  table : Identifier
  /-- Access method — defaults to btree per postgres convention. -/
  method : IndexMethod := .btree
  /-- Index columns in declaration order. -/
  columns : List IndexElem
  /-- If true, emit `CREATE INDEX IF NOT EXISTS`. -/
  ifNotExists : Bool := false
  /-- If true, emit `CREATE UNIQUE INDEX`. -/
  unique : Bool := false
  /-- Optional `WHERE <expr>` partial-index predicate. Postgres
      partial indexes only include rows matching the predicate —
      used heavily in production for `WHERE deleted_at IS NULL`,
      `WHERE creator_id IS NOT NULL`, etc. shapes that match the
      "live-row only" / "non-null only" cases the bitemporal
      schema relies on. -/
  whereExpr : Option Expr := none
  /-- Optional banner comment (header lines emitted before the
      CREATE INDEX). Same convention as `CreateFunctionStmt` /
      `CreateTableStmt`. -/
  banner : List String := []

/-- When the trigger fires relative to the targeted operation.
    `before` runs the trigger body, then (unless the body returns
    NULL) executes the operation. `after` runs the body after the
    operation. `insteadOf` replaces the operation entirely (only
    valid on views). -/
inductive TriggerTiming where
  | before     : TriggerTiming
  | after      : TriggerTiming
  | insteadOf  : TriggerTiming
deriving DecidableEq

/-- The operation that triggers the firing. Postgres allows
    multiple events on one trigger via `OR`; we model this as a
    `List TriggerEvent` on the parent statement. -/
inductive TriggerEvent where
  | insertEvent   : TriggerEvent
  | updateEvent   : TriggerEvent
  | deleteEvent   : TriggerEvent
  | truncateEvent : TriggerEvent
deriving DecidableEq

/-- Granularity of trigger firing. `row` fires once per affected
    row (`FOR EACH ROW`); `statement` fires once per statement
    (`FOR EACH STATEMENT`), the default. -/
inductive TriggerLevel where
  | row       : TriggerLevel
  | statement : TriggerLevel
deriving DecidableEq

/-- A complete CREATE TRIGGER statement. Mirrors libpg_query's
    `CreateTrigStmt` for the subset we emit:
      * named (vs anonymous) trigger
      * timing × events × table × level
      * executes a named function (no inline body — postgres
        triggers always dispatch to a function returning `trigger`)
      * optional `OR REPLACE` modifier (idempotent migration shape) -/
structure CreateTriggerStmt where
  /-- Trigger name (locally scoped to the target table). -/
  name : Identifier
  /-- BEFORE / AFTER / INSTEAD OF the operation. -/
  timing : TriggerTiming
  /-- One or more events combined with `OR`. -/
  events : List TriggerEvent
  /-- Schema-qualified target table (e.g. `graph.statement`). -/
  table : Identifier
  /-- Row vs. statement granularity. Defaults to `row` since most
      data-integrity triggers in our schema run per-row. -/
  level : TriggerLevel := .row
  /-- Schema-qualified function name to execute. The function must
      return `trigger`; the AST does not (yet) gate this — typing
      soundness is a follow-on phase. -/
  function : String
  /-- If true, emit `CREATE OR REPLACE TRIGGER` (PG 14+). -/
  orReplace : Bool := false
  /-- Optional banner comment lines (emitted before the
      CREATE TRIGGER). Same convention as the other Stmts. -/
  banner : List String := []
deriving DecidableEq

/-- A complete CREATE SCHEMA statement. Mirrors libpg_query's
    `CreateSchemaStmt` for the subset we emit:
      * named schema
      * optional `IF NOT EXISTS` (idempotent migration shape)
      * optional `AUTHORIZATION <role>` clause (most savvi-studio
        schemas use this to assign an owner role)
    Production usage in `db/migrations/000_initial_schema/`: 7
    unique schemas (`auth`, `audit`, `graph`, `ids`, `queries`,
    `util`, `webhook`) — 5 with AUTHORIZATION, 2 without. -/
structure CreateSchemaStmt where
  /-- Schema name (e.g. `graph`, `auth`). -/
  name : Identifier
  /-- If true, emit `CREATE SCHEMA IF NOT EXISTS` — the idempotent
      shape used everywhere in `db/migrations/000_initial_schema/`. -/
  ifNotExists : Bool := false
  /-- Optional `AUTHORIZATION <role>` clause assigning the schema's
      owner role. Required when the migration runs as a higher-
      privilege principal and the schema should be owned by a more
      restricted role. -/
  authorization : Option String := none
  /-- Optional banner comment lines (emitted before the
      CREATE SCHEMA). Same convention as the other Stmts. -/
  banner : List String := []
deriving DecidableEq

/-- A complete CREATE DOMAIN statement. Mirrors libpg_query's
    `CreateDomainStmt` for the subset we emit:
      * schema-qualified domain name
      * underlying base type (a closed `PgType`)
      * optional CHECK constraint whose expression refers to the
        value being checked via `Expr.var "value"` (postgres's
        special DOMAIN-context identifier)
      * optional banner comment

    DOMAIN is postgres's mechanism for refining a base type with
    a validation predicate. The savvi-studio schema uses it for
    `ids.dns_name` (RFC 1035), `ids.dns_label` (RFC 1123),
    `ids.pg_identifier` (lowercase + 63-char limit), and
    `ids.bit_count` (1..63 range). Each becomes one
    `Stmt.createDomain` value during the Tier-A sweep.

    Note: postgres's `CREATE DOMAIN` does not support
    `IF NOT EXISTS`. Idempotency is provided by the migration
    runner's state tracking, not the DDL itself. -/
structure CreateDomainStmt where
  /-- Schema-qualified domain name (e.g. `ids.dns_name`). -/
  name : Identifier
  /-- Underlying PG type that this domain refines. -/
  baseType : PgType
  /-- Optional CHECK constraint expression. References the value
      under check via `Expr.var "value"`. -/
  check : Option Expr := none
  /-- Optional banner comment lines. -/
  banner : List String := []

/-- A field in a composite TYPE. The field type is a closed
    `PgType`; types that reference user-defined types or arrays
    will need a future widening (e.g. `PgType.userDefined : String → PgType`). -/
structure CompositeField where
  name : String
  type : PgType
deriving DecidableEq

/-- The shape of a `CREATE TYPE` statement. Postgres supports
    composite (record-like) types and enum types as the two
    structural forms we need for the savvi-studio schema.

    Mirrors libpg_query's `CompositeTypeStmt` / `CreateEnumStmt`
    split. -/
inductive TypeShape where
  /-- Composite (record) type: `AS (field1 t1, field2 t2, ...)`. -/
  | composite (fields : List CompositeField) : TypeShape
  /-- Enum type: `AS ENUM ('v1', 'v2', ...)`. -/
  | enum      (variants : List String)       : TypeShape
deriving DecidableEq

/-- A complete CREATE TYPE statement. Mirrors libpg_query's
    `CompositeTypeStmt` / `CreateEnumStmt` for the subset we emit.

    The savvi-studio schema uses CREATE TYPE for composite records
    (e.g. `queries.page_info`, `queries.cursor`,
    `graph.statement_input`) and enums (e.g.
    `graph.traversal_direction`). Each becomes one
    `Stmt.createType` value during the Tier-A sweep.

    Note: postgres's `CREATE TYPE` does not support
    `IF NOT EXISTS`. Idempotency is provided by the migration
    runner's state tracking, not the DDL itself. -/
structure CreateTypeStmt where
  /-- Schema-qualified type name (e.g. `queries.page_info`). -/
  name : Identifier
  /-- Composite or enum shape. -/
  shape : TypeShape
  /-- Optional banner comment lines. -/
  banner : List String := []
deriving DecidableEq

/-- The command a row-level security policy applies to. `all` is
    postgres's default when `FOR` is omitted (covers SELECT, INSERT,
    UPDATE, DELETE). Mirrors libpg_query's `cmd_name` field on
    `CreatePolicyStmt`. -/
inductive PolicyCommand where
  | all      : PolicyCommand
  | select   : PolicyCommand
  | insert   : PolicyCommand
  | update   : PolicyCommand
  | delete   : PolicyCommand
deriving DecidableEq

/-- Render a `PolicyCommand` as the SQL keyword (used in
    `FOR …` clauses). -/
def PolicyCommand.toSql : PolicyCommand → String
  | .all    => "ALL"
  | .select => "SELECT"
  | .insert => "INSERT"
  | .update => "UPDATE"
  | .delete => "DELETE"

/-- A complete CREATE POLICY statement (row-level security).
    Mirrors libpg_query's `CreatePolicyStmt` for the subset we emit:
      * named policy on a schema-qualified table
      * `FOR <command>` clause (defaults to ALL)
      * optional `USING (expr)` — the visibility predicate for
        SELECT / UPDATE / DELETE
      * optional `WITH CHECK (expr)` — the write predicate for
        INSERT / UPDATE

    For INSERT-only policies, `using_` is meaningless (postgres
    rejects it). For SELECT-only policies, `withCheck` is
    meaningless. The AST allows both fields independently so each
    can be emitted; type-soundness rules (Phase B) will gate which
    combinations are valid per command.

    `permissive` defaults to true (the postgres default — permissive
    policies OR together; restrictive policies AND together).

    Note: postgres's `CREATE POLICY` does not support `IF NOT EXISTS`. -/
structure CreatePolicyStmt where
  /-- Policy name (locally scoped to the target table). -/
  name : Identifier
  /-- Schema-qualified target table (e.g. `graph.statement`). -/
  table : Identifier
  /-- Which command the policy applies to. Defaults to ALL. -/
  command : PolicyCommand := .all
  /-- Optional `USING (expr)` visibility predicate. -/
  using_ : Option Expr := none
  /-- Optional `WITH CHECK (expr)` write predicate. -/
  withCheck : Option Expr := none
  /-- Optional banner comment lines. -/
  banner : List String := []

/-- What an `ALTER TABLE` does to its target.

    Deliberately narrow: the row-level-security toggles, which are the ones a
    schema emitter cannot currently express at all. `ADD COLUMN` / `DROP COLUMN`
    are the obvious next arms and are omitted until something needs them —
    a migration DSL that can drop columns is a different safety question.

    ENABLE vs FORCE is the distinction that motivates this whole structure, and
    it is not cosmetic. `ENABLE` makes policies apply to ordinary roles but
    leaves the table OWNER exempt; `FORCE` removes that exemption. A schema with
    ENABLE and no FORCE, read by a service that owns its tables, has policies
    that never run — and `pg_policy` looks identical either way, so nothing
    surfaces it. That is a property worth having a kernel able to state. -/
inductive AlterTableAction where
  | enableRowLevelSecurity   : AlterTableAction
  | disableRowLevelSecurity  : AlterTableAction
  | forceRowLevelSecurity    : AlterTableAction
  | noForceRowLevelSecurity  : AlterTableAction
deriving DecidableEq, Repr

/-- Render one action as its SQL clause. -/
def AlterTableAction.toSql : AlterTableAction → String
  | .enableRowLevelSecurity  => "ENABLE ROW LEVEL SECURITY"
  | .disableRowLevelSecurity => "DISABLE ROW LEVEL SECURITY"
  | .forceRowLevelSecurity   => "FORCE ROW LEVEL SECURITY"
  | .noForceRowLevelSecurity => "NO FORCE ROW LEVEL SECURITY"

/-- `ALTER TABLE <name> <action>;`

    One action per statement, matching postgres's own rendering and keeping the
    emitted migration diffable line by line — a multi-action ALTER is harder to
    read in a review than two statements, and postgres accepts both. -/
structure AlterTableStmt where
  /-- Schema-qualified target (e.g. `graph.resource`). -/
  name : Identifier
  /-- The action to apply. -/
  action : AlterTableAction
  /-- Optional banner comment lines. -/
  banner : List String := []
deriving DecidableEq, Repr

/-- A top-level SQL statement. Grows as the savvi-studio schema sweep
    encounters new shapes. -/
inductive Stmt where
  | createFunction               : CreateFunctionStmt → Stmt
  | createTable                  : CreateTableStmt → Stmt
  | createIndex                  : CreateIndexStmt → Stmt
  | createSqlFunction            : CreateSqlFunctionStmt → Stmt
  | createSetReturningFunction   : CreateSetReturningFunctionStmt → Stmt
  | createTableReturningFunction : CreateTableReturningFunctionStmt → Stmt
  | createScalarSelectFunction   : CreateScalarSelectFunctionStmt → Stmt
  | createRecursiveCteFunction   : CreateRecursiveCteFunctionStmt → Stmt
  | createTrigger                : CreateTriggerStmt → Stmt
  | createSchema                 : CreateSchemaStmt → Stmt
  | createDomain                 : CreateDomainStmt → Stmt
  | createType                   : CreateTypeStmt → Stmt
  | createPolicy                 : CreatePolicyStmt → Stmt
  | alterTable                   : AlterTableStmt → Stmt


end Pg.Stmt
