-- AUTO-GENERATED by @rules_postgres//tools:pgpb_codegen.
-- Source: pg_query.proto @ libpg_query 17-6.2.2.
-- Re-run: bazel run @rules_postgres//tools/pgpb_codegen:regenerate
-- DO NOT EDIT BY HAND.

namespace Pg.Query


/-! ## Enums -/

inductive RoleSpecType where
  | undefined           -- 0 (ROLE_SPEC_TYPE_UNDEFINED)
  | cstring             -- 1 (ROLESPEC_CSTRING)
  | currentRole         -- 2 (ROLESPEC_CURRENT_ROLE)
  | currentUser         -- 3 (ROLESPEC_CURRENT_USER)
  | sessionUser         -- 4 (ROLESPEC_SESSION_USER)
  | public_             -- 5 (ROLESPEC_PUBLIC)
deriving DecidableEq, Repr, Inhabited

inductive PartitionStrategy where
  | undefined           -- 0 (PARTITION_STRATEGY_UNDEFINED)
  | list                -- 1 (PARTITION_STRATEGY_LIST)
  | range               -- 2 (PARTITION_STRATEGY_RANGE)
  | hash                -- 3 (PARTITION_STRATEGY_HASH)
deriving DecidableEq, Repr, Inhabited

inductive OnCommitAction where
  | undefined           -- 0 (ON_COMMIT_ACTION_UNDEFINED)
  | noop                -- 1 (ONCOMMIT_NOOP)
  | preserveRows        -- 2 (ONCOMMIT_PRESERVE_ROWS)
  | deleteRows          -- 3 (ONCOMMIT_DELETE_ROWS)
  | drop                -- 4 (ONCOMMIT_DROP)
deriving DecidableEq, Repr, Inhabited

/-! ## Messages -/

mutual

structure RawStmt where
  stmt               : _root_.ByteArray             := _root_.ByteArray.empty
  stmtLocation       : _root_.Int32                 := 0
  stmtLen            : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure ParseResult where
  version            : _root_.Int32                 := 0
  stmts              : _root_.List RawStmt          := []
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure Alias where
  aliasname          : _root_.String                := ""
  colnames           : _root_.List _root_.ByteArray := []
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure RangeVar where
  catalogname        : _root_.String                := ""
  schemaname         : _root_.String                := ""
  relname            : _root_.String                := ""
  inh                : _root_.Bool                  := false
  relpersistence     : _root_.String                := ""
  alias              : _root_.Option Alias          := none
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure TypeName where
  names              : _root_.List _root_.ByteArray := []
  typeOid            : _root_.UInt32                := 0
  setof              : _root_.Bool                  := false
  pctType            : _root_.Bool                  := false
  typmods            : _root_.List _root_.ByteArray := []
  typemod            : _root_.Int32                 := 0
  arrayBounds        : _root_.List _root_.ByteArray := []
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CollateClause where
  arg                : _root_.ByteArray             := _root_.ByteArray.empty
  collname           : _root_.List _root_.ByteArray := []
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure RoleSpec where
  roletype           : RoleSpecType                 := .undefined
  rolename           : _root_.String                := ""
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure PartitionSpec where
  strategy           : PartitionStrategy            := .undefined
  partParams         : _root_.List _root_.ByteArray := []
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure PartitionBoundSpec where
  strategy           : _root_.String                := ""
  isDefault          : _root_.Bool                  := false
  modulus            : _root_.Int32                 := 0
  remainder          : _root_.Int32                 := 0
  listdatums         : _root_.List _root_.ByteArray := []
  lowerdatums        : _root_.List _root_.ByteArray := []
  upperdatums        : _root_.List _root_.ByteArray := []
  location           : _root_.Int32                 := 0
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CreateSchemaStmt where
  schemaname         : _root_.String                := ""
  authrole           : _root_.Option RoleSpec       := none
  schemaElts         : _root_.List _root_.ByteArray := []
  ifNotExists        : _root_.Bool                  := false
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CreateStmt where
  relation           : _root_.Option RangeVar       := none
  tableElts          : _root_.List _root_.ByteArray := []
  inhRelations       : _root_.List _root_.ByteArray := []
  partbound          : _root_.Option PartitionBoundSpec := none
  partspec           : _root_.Option PartitionSpec  := none
  ofTypename         : _root_.Option TypeName       := none
  constraints        : _root_.List _root_.ByteArray := []
  options            : _root_.List _root_.ByteArray := []
  oncommit           : OnCommitAction               := .undefined
  tablespacename     : _root_.String                := ""
  accessMethod       : _root_.String                := ""
  ifNotExists        : _root_.Bool                  := false
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CreateDomainStmt where
  domainname         : _root_.List _root_.ByteArray := []
  typeName           : _root_.Option TypeName       := none
  collClause         : _root_.Option CollateClause  := none
  constraints        : _root_.List _root_.ByteArray := []
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CreateFunctionStmt where
  isProcedure        : _root_.Bool                  := false
  replace            : _root_.Bool                  := false
  funcname           : _root_.List _root_.ByteArray := []
  parameters         : _root_.List _root_.ByteArray := []
  returnType         : _root_.Option TypeName       := none
  options            : _root_.List _root_.ByteArray := []
  sqlBody            : _root_.ByteArray             := _root_.ByteArray.empty
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CompositeTypeStmt where
  typevar            : _root_.Option RangeVar       := none
  coldeflist         : _root_.List _root_.ByteArray := []
-- deriving Inhabited (deferred — expensive in mutual blocks)

structure CreateEnumStmt where
  typeName           : _root_.List _root_.ByteArray := []
  vals               : _root_.List _root_.ByteArray := []
-- deriving Inhabited (deferred — expensive in mutual blocks)

end  -- mutual

end Pg.Query
