"""`pg_meson_configure` — `meson_configure` (from rules_meson) wrapped
with PostgreSQL-specific defaults.

The general-purpose meson → Bazel tooling lives in `rules_meson`. This
file is a thin shim that supplies:

  - PG-tailored meson_options that disable every optional Postgres dep
    so meson setup doesn't fail probing for ICU / SSL / LLVM / zlib /
    etc. AST extraction only cares about source files + -I/-D flags,
    not the linked libs.
  - The `pre_remove` list of overlay headers that `@postgres_src` lays
    into `src/include/` for its legacy `pg_common_string` cc_library
    probe. Those overlay headers confuse meson's clean-checkout
    heuristic.

If you need a meson configure target for a non-Postgres project, use
`@rules_meson//meson:meson_configure.bzl%meson_configure` directly.

Wiring (typical):

    load("@rules_postgres//postgres:meson.bzl", "pg_meson_configure")

    pg_meson_configure(
        name = "pg17_compdb",
        srcs = ["@postgres_src//:all_source"],
        marker = "@postgres_src//:meson.build",
    )

    # downstream:
    c_ast_dump_from_compdb(
        compile_commands = ":pg17_compdb",
        srcs = ["@postgres_src//:all_c_sources"],
        ...
    )
"""

load(
    "@rules_meson//meson:meson_configure.bzl",
    _meson_configure = "meson_configure",
)

# PostgreSQL 17 meson option defaults. Disables every optional dep.
#
# Notes:
#   - `ssl` and `uuid` use `combo` typing in Postgres' meson_options.txt
#     (specific choices instead of the auto/disabled/enabled feature
#     trio), so they take `none` rather than `disabled`.
#   - `libcurl` was added in PG 18; not present in PG 17.
_PG_DEFAULT_MESON_OPTIONS = [
    "-Dbuildtype=debug",
    "-Dicu=disabled",
    "-Dlz4=disabled",
    "-Dzstd=disabled",
    "-Dbonjour=disabled",
    "-Dbsd_auth=disabled",
    "-Dgssapi=disabled",
    "-Dldap=disabled",
    "-Dlibxml=disabled",
    "-Dlibxslt=disabled",
    "-Dllvm=disabled",
    "-Dnls=disabled",
    "-Dpam=disabled",
    "-Dplperl=disabled",
    "-Dplpython=disabled",
    "-Dpltcl=disabled",
    "-Dreadline=disabled",
    "-Dselinux=disabled",
    "-Dssl=none",
    "-Dsystemd=disabled",
    "-Duuid=none",
    "-Dzlib=disabled",
    "-Ddocs=disabled",
    "-Ddtrace=disabled",
    "-Dtap_tests=disabled",
]

# Overlay headers that `@postgres_src` symlinks into `src/include/` for
# its legacy `pg_common_string` cc_library probe. Removed before meson
# runs so the source tree looks "clean" to meson's checkout heuristic.
_PG_OVERLAY_HEADERS_TO_REMOVE = [
    "src/include/pg_config.h",
    "src/include/pg_config_ext.h",
    "src/include/pg_config_os.h",
]

def pg_meson_configure(name, srcs, marker, meson_options = None, **kwargs):
    """Run hermetic `meson setup` against a PostgreSQL source tree.

    Args:
      name: target name.
      srcs: filegroups covering the Postgres source tree. Typically
        `["@postgres_src//:all_source"]`.
      marker: label of the meson.build file at the source root.
        Typically `"@postgres_src//:meson.build"`.
      meson_options: override the default PG meson options list.
        Defaults to a list that disables every optional dep so meson
        setup succeeds without requiring ICU / SSL / etc. installed.
      **kwargs: forwarded to the underlying rules_meson `meson_configure`.

    Output: `:<name>` resolves to compile_commands.json (single file in
    DefaultInfo). The meson log lives in the `log` output group.

    Codegen behavior: `build_custom_targets = True` by default — Postgres'
    backend TUs #include headers like `utils/errcodes.h`,
    `nodes/nodetags.h`, `utils/fmgroids.h` that are generated by Perl
    scripts declared as meson custom_targets. Without this, only
    frontend TUs (libpgcommon, libpgport) extract cleanly.
    """
    _meson_configure(
        name = name,
        srcs = srcs,
        marker = marker,
        meson_options = meson_options if meson_options != None else _PG_DEFAULT_MESON_OPTIONS,
        pre_remove = _PG_OVERLAY_HEADERS_TO_REMOVE,
        build_custom_targets = True,
        **kwargs
    )
