import Pg.Ir.Emit.FloatToIntCommon

/-!
# Pg.Ir.Emit.FloatToInt — Rust emit for the float-to-int cast V1 fmgr cluster.
-/

namespace Pg.Ir.Emit.FloatToInt.Rust

open Pg.Ir.Emit.FloatToInt (CastBody CastFamily families)

def renderBody (fam : CastFamily) : String :=
  let prelude :=
    "    let f = &mut *fcinfo;\n" ++
    "    let mut num = " ++ fam.decoder ++ "(f.args[0].value);\n"
  let rintf := if fam.rustFloatTy == "f32" then "rint_f32" else "rint_f64"
  match fam.body with
  | .toInt16 =>
      prelude ++
      "    num = " ++ rintf ++ "(num);\n" ++
      -- Upper bound is the exclusive power of two (`>= 32768.0`), matching
      -- Postgres' FLOAT*_FITS_IN_INT16 (`< -MIN`). `> 32767.0` would, as f32,
      -- wrongly admit 32768.0 (32767.0f rounds up) and saturate-cast it.
      "    if num.is_nan() || num < -32768.0 || num >= 32768.0 {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(num as " ++ fam.rustIntTy ++ ")\n"
  | .toInt32 =>
      prelude ++
      "    num = " ++ rintf ++ "(num);\n" ++
      -- Exclusive 2^31 upper bound, matching Postgres' FLOAT*_FITS_IN_INT32.
      -- `> 2147483647.0` would, as f32, wrongly admit 2147483648.0 (the literal
      -- 2147483647.0f rounds up to 2^31) and saturate-cast it to i32::MAX.
      "    if num.is_nan() || num < -2147483648.0 || num >= 2147483648.0 {\n" ++
      "        pg_ereport_numeric_value_out_of_range();\n" ++
      "        return 0;\n" ++
      "    }\n" ++
      "    " ++ fam.encoder ++ "(num as " ++ fam.rustIntTy ++ ")\n"

def renderFn (fam : CastFamily) : String :=
  "#[no_mangle]\n" ++
  "pub unsafe extern \"C\" fn " ++ fam.fnName ++
    "(fcinfo: *mut FunctionCallInfoBaseData) -> u64 {\n" ++
  renderBody fam ++
  "}\n"

def rustSource : String :=
  let header :=
    "// Generated by `rules_postgres/lean/Pg/Ir/Emit/FloatToInt.lean`.\n" ++
    "// DO NOT EDIT BY HAND. Regenerate via\n" ++
    "// `rules_postgres/tools/regen/regen-float-to-int.sh`.\n" ++
    "//\n" ++
    "// Float-to-int cast V1 fmgr cluster: 4 functions = {ftoi2, ftoi4, dtoi2, dtoi4}.\n" ++
    "// Each body decodes a float argument, rounds it via rint(), checks for NaN\n" ++
    "// and out-of-range values, and returns the truncated int result.\n" ++
    "\n" ++
    "#![allow(clippy::missing_safety_doc)]\n" ++
    "\n" ++
    "use pg_fcinfo::{\n" ++
    "    decode_f32, decode_f64,\n" ++
    "    encode_i16, encode_i32,\n" ++
    "    pg_ereport_numeric_value_out_of_range,\n" ++
    "    FunctionCallInfoBaseData,\n" ++
    "};\n" ++
    "\n" ++
    "/// Banker's rounding (round to nearest, ties to even) — matches C's rint().\n" ++
    "fn rint_f32(x: f32) -> f32 {\n" ++
    "    let truncated = x.trunc();\n" ++
    "    let frac = x - truncated;\n" ++
    "    if frac == 0.5 {\n" ++
    "        let int_part = truncated as i32;\n" ++
    "        if int_part % 2 == 0 {\n" ++
    "            truncated\n" ++
    "        } else {\n" ++
    "            truncated + 1.0\n" ++
    "        }\n" ++
    "    } else if frac == -0.5 {\n" ++
    "        let int_part = truncated as i32;\n" ++
    "        if int_part % 2 == 0 {\n" ++
    "            truncated\n" ++
    "        } else {\n" ++
    "            truncated - 1.0\n" ++
    "        }\n" ++
    "    } else {\n" ++
    "        x.round()\n" ++
    "    }\n" ++
    "}\n" ++
    "\n" ++
    "/// Banker's rounding (round to nearest, ties to even) — matches C's rint().\n" ++
    "fn rint_f64(x: f64) -> f64 {\n" ++
    "    let truncated = x.trunc();\n" ++
    "    let frac = x - truncated;\n" ++
    "    if frac == 0.5 {\n" ++
    "        let int_part = truncated as i64;\n" ++
    "        if int_part % 2 == 0 {\n" ++
    "            truncated\n" ++
    "        } else {\n" ++
    "            truncated + 1.0\n" ++
    "        }\n" ++
    "    } else if frac == -0.5 {\n" ++
    "        let int_part = truncated as i64;\n" ++
    "        if int_part % 2 == 0 {\n" ++
    "            truncated\n" ++
    "        } else {\n" ++
    "            truncated - 1.0\n" ++
    "        }\n" ++
    "    } else {\n" ++
    "        x.round()\n" ++
    "    }\n" ++
    "}\n"
  Id.run do
    let mut s := header
    for fam in families do
      s := s ++ "\n" ++ renderFn fam
    return s

end Pg.Ir.Emit.FloatToInt.Rust

def main : IO Unit := IO.print Pg.Ir.Emit.FloatToInt.Rust.rustSource
