import Pg.Ir.Types
import Pg.Ir.Datum
import Pg.Ir.Emit.TidCommon

/-!
# Pg.Ir.Emit.TidC — codegen real-style Postgres C source for tid cluster.

Sibling to `Pg.Ir.Emit.Tid` (which emits Rust). Same `TidCmpFamily`, `TidClampFamily`,
and `TidHashFamily` tables from `TidCommon`, but renders **Postgres-idiomatic C**
instead of Rust.

The point: produce C that's structurally identical to what's in real
`src/backend/utils/adt/tid.c` after clang preprocessing, so that an AST-level
diff between the two reveals algorithmic divergence (vs. style differences).

The real Postgres code:
  - tideq/tidne/tidlt/tidle/tidgt/tidge all call ItemPointerCompare
  - bttidcmp also calls ItemPointerCompare
  - tidlarger/tidsmaller call ItemPointerCompare
  - hashtid and hashtidextended call hash_any / hash_any_extended

Our Lean emit must mirror this delegation pattern, not inline the bodies.
-/

namespace Pg.Ir.Emit.TidC

open Pg.Ir.Emit (TidCmpFamily TidClampFamily TidHashFamily tidCmpOps tidClampFamilies tidHashFamilies)

/-- Render one tid comparison function (eq/ne/lt/le/gt/ge).
These delegate to ItemPointerCompare, mirroring Postgres exactly. -/
def renderCmpFn (fam : TidCmpFamily) : String :=
  let fnName := "tid" ++ fam.suffix
  let opStr := match fam.cmpOp with
    | "< 0"  => "<"
    | "<= 0" => "<="
    | "== 0" => "=="
    | "!= 0" => "!="
    | ">= 0" => ">="
    | "> 0"  => ">"
    | _      => "unknown_op"
  "Datum\n" ++
  fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tItemPointer arg1 = PG_GETARG_ITEMPOINTER(0);\n" ++
  "\tItemPointer arg2 = PG_GETARG_ITEMPOINTER(1);\n" ++
  "\n" ++
  "\tPG_RETURN_BOOL(ItemPointerCompare(arg1, arg2) " ++ opStr ++ " 0);\n" ++
  "}\n"

/-- Render the bttidcmp function. -/
def renderCmpInternal : String :=
  "Datum\n" ++
  "bttidcmp(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tItemPointer arg1 = PG_GETARG_ITEMPOINTER(0);\n" ++
  "\tItemPointer arg2 = PG_GETARG_ITEMPOINTER(1);\n" ++
  "\n" ++
  "\tPG_RETURN_INT32(ItemPointerCompare(arg1, arg2));\n" ++
  "}\n"

/-- Render one tid clamp function (tidlarger/tidsmaller). -/
def renderClampFn (fam : TidClampFamily) : String :=
  let fnName := fam.fnName
  -- `cmpOp` is already a full predicate like ">= 0" / "<= 0" — pass
  -- through verbatim. Earlier versions of this match stripped the
  -- trailing "0", which produced syntactically invalid C
  -- (`... <= ? arg1 : arg2`); Gate 3 caught it.
  let opStr := fam.cmpOp
  "Datum\n" ++
  fnName ++ "(PG_FUNCTION_ARGS)\n" ++
  "{\n" ++
  "\tItemPointer arg1 = PG_GETARG_ITEMPOINTER(0);\n" ++
  "\tItemPointer arg2 = PG_GETARG_ITEMPOINTER(1);\n" ++
  "\n" ++
  "\tPG_RETURN_ITEMPOINTER(ItemPointerCompare(arg1, arg2) " ++ opStr ++ " ? arg1 : arg2);\n" ++
  "}\n"

/-- Render one tid hash function. -/
def renderHashFn (fam : TidHashFamily) : String :=
  let fnName := fam.fnName
  if fam.extended then
    -- Declare `seed` as a local before the return — matches real PG's
    -- statement structure. Inlining `PG_GETARG_INT64(1)` directly into
    -- the call produces functionally-identical output but a CompoundStmt
    -- with 2 inner statements vs real PG's 3, which Gate 3's structural
    -- diff flags.
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tItemPointer key = PG_GETARG_ITEMPOINTER(0);\n" ++
    "\tuint64\t\tseed = PG_GETARG_INT64(1);\n" ++
    "\n" ++
    "\treturn hash_any_extended((unsigned char *) key,\n" ++
    "\t\t\t\t\t\t   sizeof(BlockIdData) + sizeof(OffsetNumber),\n" ++
    "\t\t\t\t\t\t   seed);\n" ++
    "}\n"
  else
    "Datum\n" ++
    fnName ++ "(PG_FUNCTION_ARGS)\n" ++
    "{\n" ++
    "\tItemPointer key = PG_GETARG_ITEMPOINTER(0);\n" ++
    "\n" ++
    "\treturn hash_any((unsigned char *) key,\n" ++
    "\t\t\t   sizeof(BlockIdData) + sizeof(OffsetNumber));\n" ++
    "}\n"

/-- The full C source. -/
def cSource : String :=
  let header :=
    "/* Generated by `rules_postgres/lean/Pg/Ir/Emit/TidC.lean`. */\n" ++
    "/* DO NOT EDIT BY HAND. Regenerate via */\n" ++
    "/* `rules_postgres/tools/regen/regen-tid.sh`. */\n" ++
    "\n" ++
    "/* Real-PG-style C for AST grounding. clang -ast-dump=json this\n" ++
    " * file with real Postgres' headers, then diff against the AST\n" ++
    " * for `src/backend/utils/adt/tid.c`. The shared header set is\n" ++
    " * what makes `ItemPointer`, `PG_GETARG_ITEMPOINTER`, `ItemPointerCompare`,\n" ++
    " * etc. resolve to the same types/macros on both sides, so the diff\n" ++
    " * captures algorithmic divergence rather than per-translation-unit type\n" ++
    " * resolution noise. */\n" ++
    "#include \"postgres.h\"\n" ++
    "#include \"common/hashfn.h\"\n" ++
    "#include \"storage/itemptr.h\"\n" ++
    "#include \"utils/fmgrprotos.h\"\n" ++
    "\n"
  Id.run do
    let mut s := header
    for fam in tidCmpOps do
      s := s ++ "\n" ++ renderCmpFn fam
    s := s ++ "\n" ++ renderCmpInternal
    s := s ++ "\n"
    for fam in tidClampFamilies do
      s := s ++ "\n" ++ renderClampFn fam
    s := s ++ "\n"
    for fam in tidHashFamilies do
      s := s ++ "\n" ++ renderHashFn fam
    return s

end Pg.Ir.Emit.TidC

/-- `main` entrypoint: print the C source to stdout. -/
def main : IO Unit := IO.print Pg.Ir.Emit.TidC.cSource
